import { Place } from "@/entities/Place"
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

// Define a service using a base URL and expected endpoints
export const imagesApiSlice = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: import.meta.env.VITE_IMAGES_API_BASE_URL,
  }),
  // Tag types are used for caching and invalidation.
  tagTypes: ["Places"],
  endpoints: build => ({
    getImages: build.query<Place[], number>({
      query: limit => `images?limit=${limit}`,
      providesTags: (result, error, id) => [{ type: "Places", id }],
      transformResponse: (response: PlaceApiResponseWrapper, meta, arg) => {
        return response.images?.map(responseItem =>
          MapApiReponseToEntity(responseItem),
        )
      },
    }),
  }),
})

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetImagesQuery } = imagesApiSlice

interface LatLongCoords {
  latitude: number
  longitude: number
}

interface PlaceApiResponse {
  id: number
  url: string
  coordinates: LatLongCoords
}

interface PlaceApiResponseWrapper {
  images: PlaceApiResponse[]
  count: number
}

function MapApiReponseToEntity(response: PlaceApiResponse): Place {
  return {
    id: response.id,
    description: "",
    image: response.url,
    coordinates: {
      lat: response.coordinates.latitude,
      lng: response.coordinates.longitude,
    },
  }
}
